//#define RGBLIGHT_ANIMATIONS


#pragma once
#include "config_common.h"


#define CIRQUE_PINNACLE_DIAMETER_35
#define ADC_ATTENUATE_3X
#define CIRQUE_PINNACLE_RELATIVE_MODE 0
#define CIRQUE_PINNACLE_TAP_ENABLE
#define CIRQUE_PINNACLE_SECONDARY_TAP_ENABLE
#define POINTING_DEVICE_GESTURES_SCROLL_ENABLE